version: '3'
services: 
  linux:
    image: dsifford/s3fs
    build: ./
    volumes:
        - ./src:/src
        - /lib/modules:/lib/modules:ro
    env_file: 
        - .env
    command: tail -f /dev/null
    privileged: true
    cap_add:
        - ALL
